(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"EFT_subGeV_DM_rho",
  Authors -> {"Adam Coogan", "Logan Morrison"},
  Date -> "2/13/2018",
  Institutions -> {"UC Santa Cruz"},
  Emails -> {"acoogan@ucsc.edu", "loanmorr@ucsc.edu"},
  Version -> 1};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["\\pi", Null, "0"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mpi0,
    Indices -> {} },

S[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["\\pi", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mpi,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> ComposedChar["K", Null, "0"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk0,
    Indices -> {} },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["K", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk,
    Indices -> {} },

S[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\eta",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> meta,
    Indices -> {} },

S[7] == {
    SelfConjugate -> True,
    PropagatorLabel -> s,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> ms,
    Indices -> {} },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> A,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\rho",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mrho,
    Indices -> {} },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> ml,
    Indices -> {} },

F[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> "\\chi",
    PropagatorArrow -> Forward,
    PropagatorType -> Straight,
    Mass -> mx,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];

mpi0[ ___ ] := mpi0;
mpi[ ___ ] := mpi;
mk0[ ___ ] := mk0;
mk[ ___ ] := mk;
meta[ ___ ] := meta;
ms[ ___ ] := ms;
mrho[ ___ ] := mrho;
ml[ ___ ] := ml;
mx[ ___ ] := mx;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[5] , S[5] , S[5] , S[5] ] == {{I*gc1, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[3] , -S[3] ] == {{(2*I)*b0*gc2*(mdq + 3*msq), 0}, {(6*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(6*I)*gc2, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-2*I)*b0*gc3*(mdq + msq), 0}, {(2*I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(2*I)*gc3, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] ] == {{I*b0*gc4*(mdq + 2*msq + muq), 0}, {I*gc4, 0}, {I*gc4, 0}, {(-2*I)*gc4, 0}, {(-2*I)*gc4, 0}, {I*gc4, 0}, {I*gc4, 0}},

C[ S[5] , S[5] , S[4] , -S[4] ] == {{(2*I)*b0*gc5*(3*msq + muq), 0}, {(6*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(6*I)*gc5, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*b0*gc6*(msq + muq), 0}, {(2*I)*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {(2*I)*gc6, 0}},

C[ S[5] , S[5] , S[5] , S[1] ] == {{I*gc7, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , S[1] ] == {{(-2*I)*b0*gc8*(mdq - msq), 0}, {(3*I)*gc8, 0}, {(3*I)*gc8, 0}, {(-6*I)*gc8, 0}, {(-6*I)*gc8, 0}, {(3*I)*gc8, 0}, {(3*I)*gc8, 0}},

C[ S[5] , S[4] , -S[4] , S[1] ] == {{(2*I)*b0*gc9*(msq - muq), 0}, {(3*I)*gc9, 0}, {(3*I)*gc9, 0}, {(-6*I)*gc9, 0}, {(-6*I)*gc9, 0}, {(3*I)*gc9, 0}, {(3*I)*gc9, 0}},

C[ S[5] , S[5] , S[1] , S[1] ] == {{I*gc10, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(2*I)*b0*gc11*(3*mdq + msq), 0}, {(2*I)*gc11, 0}, {(-I)*gc11, 0}, {(-I)*gc11, 0}, {(-I)*gc11, 0}, {(-I)*gc11, 0}, {(2*I)*gc11, 0}},

C[ S[4] , -S[4] , S[1] , S[1] ] == {{(2*I)*b0*gc12*(msq + 3*muq), 0}, {(2*I)*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {(2*I)*gc12, 0}},

C[ S[5] , S[1] , S[1] , S[1] ] == {{I*gc13, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{I*gc14, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] ] == {{(-I)*b0*gc15*(mdq - 2*msq + muq), 0}, {(3*I)*gc15, 0}, {(3*I)*gc15, 0}, {(-6*I)*gc15, 0}, {(-6*I)*gc15, 0}, {(3*I)*gc15, 0}, {(3*I)*gc15, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] ] == {{I*b0*gc16*(mdq - muq), 0}, {0, 0}, {(3*I)*gc16, 0}, {(-3*I)*gc16, 0}, {(-3*I)*gc16, 0}, {(3*I)*gc16, 0}, {0, 0}},

C[ S[5] , S[3] , S[4] , -S[2] ] == {{(-I)*b0*gc17*(mdq - 2*msq + muq), 0}, {(3*I)*gc17, 0}, {(3*I)*gc17, 0}, {(-6*I)*gc17, 0}, {(-6*I)*gc17, 0}, {(3*I)*gc17, 0}, {(3*I)*gc17, 0}},

C[ S[3] , S[4] , S[1] , -S[2] ] == {{I*b0*gc18*(mdq - muq), 0}, {0, 0}, {(3*I)*gc18, 0}, {(-3*I)*gc18, 0}, {(-3*I)*gc18, 0}, {(3*I)*gc18, 0}, {0, 0}},

C[ S[5] , S[5] , S[2] , -S[2] ] == {{I*gc19, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] ] == {{I*b0*gc20*(2*mdq + msq + muq), 0}, {I*gc20, 0}, {(-2*I)*gc20, 0}, {I*gc20, 0}, {I*gc20, 0}, {(-2*I)*gc20, 0}, {I*gc20, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] ] == {{I*b0*gc21*(mdq + msq + 2*muq), 0}, {I*gc21, 0}, {(-2*I)*gc21, 0}, {I*gc21, 0}, {I*gc21, 0}, {(-2*I)*gc21, 0}, {I*gc21, 0}},

C[ S[5] , S[1] , S[2] , -S[2] ] == {{I*gc22, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] ] == {{I*b0*gc23*(mdq + muq), 0}, {(2*I)*gc23, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(2*I)*gc23, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] ] == {{(-2*I)*b0*gc24*(mdq + muq), 0}, {(2*I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(2*I)*gc24, 0}},

C[ S[5] , S[5] , S[7] ] == {{(-I)*b0*gc25*(mdq + 4*msq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(972*I)*gc25*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[5] , S[5] , S[7] ] == {{I*gc26, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[7] ] == {{(-I)*b0*gc27*(mdq + msq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc27*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[3] , -S[3] , S[7] ] == {{(-I)*b0*gc28*(mdq + 3*msq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(972*I)*gc28*gsGG*Lam^3*vh^2, 0}, {(-486*I)*gc28*gsGG*Lam^3*vh^2, 0}, {(-486*I)*gc28*gsGG*Lam^3*vh^2, 0}, {(-486*I)*gc28*gsGG*Lam^3*vh^2, 0}, {(-486*I)*gc28*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc28*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] , S[7] ] == {{I*b0*gc29*(mdq + msq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc29*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc29*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc29*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc29*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc29*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc29*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] , S[7] ] == {{(-I)*b0*gc30*(mdq + 2*msq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc30*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc30*gsGG*Lam^3*vh^2, 0}, {(-648*I)*gc30*gsGG*Lam^3*vh^2, 0}, {(-648*I)*gc30*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc30*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc30*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[7] ] == {{(-I)*b0*gc31*(msq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc31*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[4] , -S[4] , S[7] ] == {{(-I)*b0*gc32*(3*msq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(972*I)*gc32*gsGG*Lam^3*vh^2, 0}, {(-486*I)*gc32*gsGG*Lam^3*vh^2, 0}, {(-486*I)*gc32*gsGG*Lam^3*vh^2, 0}, {(-486*I)*gc32*gsGG*Lam^3*vh^2, 0}, {(-486*I)*gc32*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc32*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] , S[7] ] == {{I*b0*gc33*(msq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc33*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc33*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc33*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc33*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc33*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc33*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[7] ] == {{I*gc34, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[5] , S[1] , S[7] ] == {{I*gc35, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , S[1] , S[7] ] == {{I*b0*gc36*(mdq - msq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(486*I)*gc36*gsGG*Lam^3*vh^2, 0}, {(486*I)*gc36*gsGG*Lam^3*vh^2, 0}, {(-972*I)*gc36*gsGG*Lam^3*vh^2, 0}, {(-972*I)*gc36*gsGG*Lam^3*vh^2, 0}, {(486*I)*gc36*gsGG*Lam^3*vh^2, 0}, {(486*I)*gc36*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[4] , -S[4] , S[1] , S[7] ] == {{(-I)*b0*gc37*(msq - muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(486*I)*gc37*gsGG*Lam^3*vh^2, 0}, {(486*I)*gc37*gsGG*Lam^3*vh^2, 0}, {(-972*I)*gc37*gsGG*Lam^3*vh^2, 0}, {(-972*I)*gc37*gsGG*Lam^3*vh^2, 0}, {(486*I)*gc37*gsGG*Lam^3*vh^2, 0}, {(486*I)*gc37*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[7] ] == {{(-I)*b0*gc38*(mdq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc38*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[1] , S[1] , S[7] ] == {{I*gc39, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] , S[1] , S[7] ] == {{(-I)*b0*gc40*(3*mdq + msq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc40*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc40*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc40*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc40*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc40*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc40*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[1] , S[1] , S[7] ] == {{(-I)*b0*gc41*(msq + 3*muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc41*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc41*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc41*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc41*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc41*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc41*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[1] , S[1] , S[7] ] == {{I*gc42, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[7] ] == {{I*gc43, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] , S[7] ] == {{I*b0*gc44*(mdq - 2*msq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(972*I)*gc44*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc44*gsGG*Lam^3*vh^2, 0}, {(-1944*I)*gc44*gsGG*Lam^3*vh^2, 0}, {(-1944*I)*gc44*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc44*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc44*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] , S[7] ] == {{(-I)*b0*gc45*(mdq - muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {0, 0}, {(972*I)*gc45*gsGG*Lam^3*vh^2, 0}, {(-972*I)*gc45*gsGG*Lam^3*vh^2, 0}, {(-972*I)*gc45*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc45*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , S[4] , -S[2] , S[7] ] == {{I*b0*gc46*(mdq - 2*msq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(972*I)*gc46*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc46*gsGG*Lam^3*vh^2, 0}, {(-1944*I)*gc46*gsGG*Lam^3*vh^2, 0}, {(-1944*I)*gc46*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc46*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc46*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[4] , S[1] , -S[2] , S[7] ] == {{(-I)*b0*gc47*(mdq - muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {0, 0}, {(972*I)*gc47*gsGG*Lam^3*vh^2, 0}, {(-972*I)*gc47*gsGG*Lam^3*vh^2, 0}, {(-972*I)*gc47*gsGG*Lam^3*vh^2, 0}, {(972*I)*gc47*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , S[7] ] == {{(-I)*b0*gc48*(mdq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc48*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[2] , -S[2] , S[7] ] == {{I*gc49, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] , S[7] ] == {{(-I)*b0*gc50*(2*mdq + msq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc50*gsGG*Lam^3*vh^2, 0}, {(-648*I)*gc50*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc50*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc50*gsGG*Lam^3*vh^2, 0}, {(-648*I)*gc50*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc50*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] , S[7] ] == {{(-I)*b0*gc51*(mdq + msq + 2*muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc51*gsGG*Lam^3*vh^2, 0}, {(-648*I)*gc51*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc51*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc51*gsGG*Lam^3*vh^2, 0}, {(-648*I)*gc51*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc51*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[2] , -S[2] , S[7] ] == {{I*gc52, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , S[7] ] == {{(-I)*b0*gc53*(mdq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(648*I)*gc53*gsGG*Lam^3*vh^2, 0}, {(-324*I)*gc53*gsGG*Lam^3*vh^2, 0}, {(-324*I)*gc53*gsGG*Lam^3*vh^2, 0}, {(-324*I)*gc53*gsGG*Lam^3*vh^2, 0}, {(-324*I)*gc53*gsGG*Lam^3*vh^2, 0}, {(648*I)*gc53*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , S[7] ] == {{I*b0*gc54*(mdq + muq)*(9*Lam + 4*gsGG*vs)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)), 0}, {(324*I)*gc54*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc54*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc54*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc54*gsGG*Lam^3*vh^2, 0}, {(-162*I)*gc54*gsGG*Lam^3*vh^2, 0}, {(324*I)*gc54*gsGG*Lam^3*vh^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[7] , S[7] ] == {{I*gc55, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[7] , S[7] ] == {{I*gc56, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[7] , S[7] ] == {{I*gc57, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[7] , S[7] ] == {{I*gc58, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[7] , S[7] ] == {{I*gc59, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , S[7] , S[7] ] == {{I*gc60, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{(2*I)*qe^2, 0}},

C[ S[2] , -S[2] , V[1] , V[1] ] == {{(2*I)*qe^2, 0}},

C[ S[4] , -S[4] , S[7] , V[1] , V[1] ] == {{((8*I)*gsGG*qe^2)/(9*Lam + 4*gsGG*vs), 0}},

C[ S[2] , -S[2] , S[7] , V[1] , V[1] ] == {{((8*I)*gsGG*qe^2)/(9*Lam + 4*gsGG*vs), 0}},

C[ S[5] , -S[3] , -S[4] , S[2] , V[1] ] == {{(3*I)*gc65, 0}, {(-3*I)*gc65, 0}, {(-I)*gc65, 0}, {I*gc65, 0}},

C[ S[5] , S[3] , S[4] , -S[2] , V[1] ] == {{(3*I)*gc66, 0}, {(-3*I)*gc66, 0}, {(-I)*gc66, 0}, {I*gc66, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] , V[1] ] == {{(3*I)*gc67, 0}, {(-3*I)*gc67, 0}, {(-I)*gc67, 0}, {I*gc67, 0}},

C[ S[3] , S[4] , S[1] , -S[2] , V[1] ] == {{I*gc68, 0}, {(-I)*gc68, 0}, {(-I)*gc68, 0}, {I*gc68, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] , V[1] ] == {{(-3*I)*gc69, 0}, {(3*I)*gc69, 0}, {(-I)*gc69, 0}, {I*gc69, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] , V[1] ] == {{I*gc70, 0}, {(-I)*gc70, 0}, {(-I)*gc70, 0}, {I*gc70, 0}},

C[ S[4] , -S[4] , V[1] ] == {{(-I)*gc71, 0}, {I*gc71, 0}},

C[ S[5] , S[5] , S[4] , -S[4] , V[1] ] == {{0, 0}, {0, 0}, {(-I)*gc72, 0}, {I*gc72, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] , V[1] ] == {{(-I)*gc73, 0}, {(-I)*gc73, 0}, {I*gc73, 0}, {I*gc73, 0}},

C[ S[5] , S[4] , -S[4] , S[1] , V[1] ] == {{0, 0}, {(-I)*gc74, 0}, {I*gc74, 0}, {0, 0}},

C[ S[4] , -S[4] , S[1] , S[1] , V[1] ] == {{(-I)*gc75, 0}, {I*gc75, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] , V[1] ] == {{(-I)*gc76, 0}, {I*gc76, 0}, {(-I)*gc76, 0}, {I*gc76, 0}},

C[ S[4] , -S[4] , S[7] , V[1] ] == {{(-I)*gc77, 0}, {I*gc77, 0}, {0, 0}},

C[ S[2] , -S[2] , V[1] ] == {{(-I)*gc78, 0}, {I*gc78, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , V[1] ] == {{0, 0}, {0, 0}, {(-I)*gc79, 0}, {I*gc79, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , V[1] ] == {{(-I)*gc80, 0}, {(-I)*gc80, 0}, {I*gc80, 0}, {I*gc80, 0}},

C[ S[2] , -S[2] , S[7] , V[1] ] == {{(-I)*gc81, 0}, {I*gc81, 0}, {0, 0}},

C[ S[7] , V[1] , V[1] ] == {{(-I)*gc82, 0}, {I*gc82, 0}},

C[ -F[2] , F[2] , S[7] ] == {{I*gc83, 0}, {I*gc83, 0}, {0, 0}, {0, 0}},

C[ -F[3] , F[3] , S[7] ] == {{I*gc84, 0}, {I*gc84, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , V[1] ] == {{I*gc85, 0}, {I*gc85, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , V[1] ] == {{I*gc86, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , V[1] ] == {{gc87, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] , V[1] ] == {{I*gc88, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , V[1] ] == {{I*gc89, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , V[1] ] == {{gc90, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , V[1] ] == {{I*gc91, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] , V[1] ] == {{I*gc92, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[3] , S[4] ] == {{-2*gc93, 0}, {gc93, 0}, {gc93, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] ] == {{(-I)*gc94, 0}, {I*gc94, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[5] , S[4] ] == {{-gc95, 0}, {-gc95, 0}, {2*gc95, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , S[1] ] == {{gc96, 0}, {-2*gc96, 0}, {gc96, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , -S[3] , S[2] ] == {{gc97, 0}, {-2*gc97, 0}, {gc97, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] ] == {{(-I)*gc98, 0}, {I*gc98, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , S[1] ] == {{-gc99, 0}, {gc99, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , -S[3] , S[2] ] == {{gc100, 0}, {-2*gc100, 0}, {gc100, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , -S[3] , S[4] ] == {{-2*gc101, 0}, {gc101, 0}, {gc101, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] ] == {{(-I)*gc102, 0}, {I*gc102, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , -S[4] , S[2] ] == {{gc103, 0}, {-2*gc103, 0}, {gc103, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] ] == {{0, 0}, {0, 0}, {2*fpi*GF*Vus, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[4] , -S[4] ] == {{-gc105, 0}, {-gc105, 0}, {2*gc105, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] ] == {{(-I)*gc106, 0}, {I*gc106, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , S[1] ] == {{-2*gc107, 0}, {gc107, 0}, {gc107, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[2] , -S[2] ] == {{-gc108, 0}, {-gc108, 0}, {2*gc108, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] ] == {{(-I)*gc109, 0}, {I*gc109, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[1] , S[2] ] == {{-gc110, 0}, {-gc110, 0}, {2*gc110, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[1] , S[2] ] == {{0, 0}, {-gc111, 0}, {gc111, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] ] == {{0, 0}, {0, 0}, {2*fpi*GF*Vud, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , S[2] , -S[2] ] == {{-gc113, 0}, {-gc113, 0}, {2*gc113, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , V[1] ] == {{I*gc114, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , V[1] ] == {{gc115, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] , V[1] ] == {{I*gc116, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , V[1] ] == {{I*gc117, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , V[1] ] == {{gc118, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , V[1] ] == {{I*gc119, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] , V[1] ] == {{I*gc120, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[3] , -S[4] ] == {{-2*gc121, 0}, {gc121, 0}, {gc121, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] ] == {{(-I)*gc122, 0}, {I*gc122, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , S[5] , -S[4] ] == {{-gc123, 0}, {-gc123, 0}, {2*gc123, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , S[1] ] == {{gc124, 0}, {-2*gc124, 0}, {gc124, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , S[3] , -S[2] ] == {{gc125, 0}, {-2*gc125, 0}, {gc125, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[3] , -S[2] ] == {{-2*gc126, 0}, {gc126, 0}, {gc126, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[3] , -S[4] ] == {{gc127, 0}, {-2*gc127, 0}, {gc127, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] ] == {{(-I)*gc128, 0}, {I*gc128, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] ] == {{(-I)*gc129, 0}, {I*gc129, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , S[1] ] == {{-gc130, 0}, {gc130, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[4] , -S[4] , -S[2] ] == {{-2*gc131, 0}, {gc131, 0}, {gc131, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[4] , -S[4] , -S[4] ] == {{-2*gc132, 0}, {gc132, 0}, {gc132, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] ] == {{0, 0}, {0, 0}, {2*fpi*GF*Vus, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] ] == {{(-I)*gc134, 0}, {I*gc134, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , S[1] ] == {{-2*gc135, 0}, {gc135, 0}, {gc135, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[2] , -S[2] ] == {{gc136, 0}, {-2*gc136, 0}, {gc136, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] ] == {{(-I)*gc137, 0}, {I*gc137, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , S[1] , -S[2] ] == {{-gc138, 0}, {-gc138, 0}, {2*gc138, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , S[1] , -S[2] ] == {{0, 0}, {-gc139, 0}, {gc139, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[2] , -S[2] , -S[2] ] == {{-2*gc140, 0}, {gc140, 0}, {gc140, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] ] == {{0, 0}, {0, 0}, {2*fpi*GF*Vud, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , S[7] , V[1] ] == {{gc142, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[7] , V[1] ] == {{gc143, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , S[7] ] == {{(-I)*gc144, 0}, {I*gc144, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , S[7] ] == {{(-I)*gc145, 0}, {I*gc145, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] , S[7] ] == {{(-I)*gc146, 0}, {I*gc146, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[7] ] == {{gc147, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , S[7] ] == {{(-I)*gc148, 0}, {I*gc148, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] , S[7] ] == {{(-I)*gc149, 0}, {I*gc149, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , S[7] ] == {{gc150, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , S[7] , V[1] ] == {{gc151, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[7] , V[1] ] == {{gc152, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , S[7] ] == {{(-I)*gc153, 0}, {I*gc153, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] , S[7] ] == {{(-I)*gc154, 0}, {I*gc154, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , S[7] ] == {{(-I)*gc155, 0}, {I*gc155, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[7] ] == {{gc156, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , S[7] ] == {{(-I)*gc157, 0}, {I*gc157, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] , S[7] ] == {{(-I)*gc158, 0}, {I*gc158, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , S[7] ] == {{gc159, 0}, {0, 0}, {0, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> (b0*(mdq + 16*msq + muq))/(9*fpi^2),
     gc2 -> 1/(12*fpi^2),
     gc3 -> -1/(3*fpi^2),
     gc4 -> 1/(6*fpi^2),
     gc5 -> 1/(12*fpi^2),
     gc6 -> -1/(3*fpi^2),
     gc7 -> -(b0*(mdq - muq))/(3*Sqrt[3]*fpi^2),
     gc8 -> 1/(12*Sqrt[3]*fpi^2),
     gc9 -> -1/(12*Sqrt[3]*fpi^2),
     gc10 -> (b0*(mdq + muq))/(3*fpi^2),
     gc11 -> 1/(12*fpi^2),
     gc12 -> 1/(12*fpi^2),
     gc13 -> -((b0*(mdq - muq))/(Sqrt[3]*fpi^2)),
     gc14 -> (b0*(mdq + muq))/fpi^2,
     gc15 -> -1/(6*Sqrt[6]*fpi^2),
     gc16 -> -1/(6*Sqrt[2]*fpi^2),
     gc17 -> -1/(6*Sqrt[6]*fpi^2),
     gc18 -> -1/(6*Sqrt[2]*fpi^2),
     gc19 -> (b0*(mdq + muq))/(3*fpi^2),
     gc20 -> 1/(6*fpi^2),
     gc21 -> 1/(6*fpi^2),
     gc22 -> -(b0*(mdq - muq))/(3*Sqrt[3]*fpi^2),
     gc23 -> 1/(3*fpi^2),
     gc24 -> -1/(3*fpi^2),
     gc25 -> -1/(243*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc26 -> -(b0*(mdq + 16*msq + muq)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)))/(729*fpi^2*Lam^3*vh^2),
     gc27 -> -1/(81*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc28 -> 1/(486*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc29 -> -2/(243*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc30 -> 1/(486*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc31 -> -1/(81*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc32 -> 1/(486*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc33 -> -2/(243*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc34 -> -(b0*(mdq - muq)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)))/(81*Sqrt[3]*Lam^3*vh^2),
     gc35 -> (b0*(mdq - muq)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)))/(243*Sqrt[3]*fpi^2*Lam^3*vh^2),
     gc36 -> 1/(486*Sqrt[3]*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc37 -> -1/(486*Sqrt[3]*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc38 -> -1/(81*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc39 -> -(b0*(mdq + muq)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)))/(243*fpi^2*Lam^3*vh^2),
     gc40 -> 1/(486*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc41 -> 1/(486*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc42 -> (b0*(mdq - muq)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)))/(81*Sqrt[3]*fpi^2*Lam^3*vh^2),
     gc43 -> -(b0*(mdq + muq)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)))/(81*fpi^2*Lam^3*vh^2),
     gc44 -> -1/(486*Sqrt[6]*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc45 -> -1/(486*Sqrt[2]*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc46 -> -1/(486*Sqrt[6]*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc47 -> -1/(486*Sqrt[2]*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc48 -> -1/(81*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc49 -> -(b0*(mdq + muq)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)))/(243*fpi^2*Lam^3*vh^2),
     gc50 -> 1/(486*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc51 -> 1/(486*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc52 -> (b0*(mdq - muq)*(27*gsff^2*Lam^2*vs*(3*Lam + 4*gsGG*vs) - 2*gsGG*vh^2*(27*Lam^2 - 30*gsGG*Lam*vs + 8*gsGG^2*vs^2) + gsff*(-81*Lam^3*vh + 48*gsGG^2*Lam*vh*vs^2)))/(243*Sqrt[3]*fpi^2*Lam^3*vh^2),
     gc53 -> 1/(243*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc54 -> -2/(243*fpi^2*Lam^3*vh^2*(9*Lam + 4*gsGG*vs)),
     gc55 -> (4*b0*gsGG*(mdq + 4*msq + muq)*(9*gsff*Lam - 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(243*Lam^3*vh^2),
     gc56 -> (4*b0*gsGG*(mdq + msq)*(9*gsff*Lam - 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(81*Lam^3*vh^2),
     gc57 -> (4*b0*gsGG*(msq + muq)*(9*gsff*Lam - 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(81*Lam^3*vh^2),
     gc58 -> (4*b0*gsGG*(mdq - muq)*(-9*gsff*Lam + 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(81*Sqrt[3]*Lam^3*vh^2),
     gc59 -> (4*b0*gsGG*(mdq + muq)*(9*gsff*Lam - 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(81*Lam^3*vh^2),
     gc60 -> (4*b0*gsGG*(mdq + muq)*(9*gsff*Lam - 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(81*Lam^3*vh^2),
     gc65 -> -qe/(2*Sqrt[6]*fpi^2),
     gc66 -> qe/(2*Sqrt[6]*fpi^2),
     gc67 -> -qe/(6*fpi^2),
     gc68 -> qe/(2*Sqrt[2]*fpi^2),
     gc69 -> -qe/(6*fpi^2),
     gc70 -> -qe/(2*Sqrt[2]*fpi^2),
     gc71 -> qe,
     gc72 -> -qe/(2*fpi^2),
     gc73 -> (-4*qe)/(3*fpi^2),
     gc74 -> -qe/(2*Sqrt[3]*fpi^2),
     gc75 -> -qe/(6*fpi^2),
     gc76 -> (-2*qe)/(3*fpi^2),
     gc77 -> (4*gsGG*qe)/(9*Lam + 4*gsGG*vs),
     gc78 -> qe,
     gc79 -> (-2*qe)/(3*fpi^2),
     gc80 -> (-4*qe)/(3*fpi^2),
     gc81 -> (4*gsGG*qe)/(9*Lam + 4*gsGG*vs),
     gc82 -> -((alphaEM*gsFF)/(Lam*Pi)),
     gc83 -> -gsll,
     gc84 -> -gsxx,
     gc85 -> -qe,
     gc86 -> Sqrt[2]*GF*qe*Vud,
     gc87 -> -2*fpi*GF*qe*Vud,
     gc88 -> -2*GF*qe*Vud,
     gc89 -> -(Sqrt[3]*GF*qe*Vus),
     gc90 -> -2*fpi*GF*qe*Vus,
     gc91 -> -(GF*qe*Vus),
     gc92 -> Sqrt[2]*GF*qe*Vus,
     gc93 -> (Sqrt[2/3]*GF*Vud)/fpi,
     gc94 -> Sqrt[3]*GF*Vus,
     gc95 -> -((GF*Vus)/fpi),
     gc96 -> (GF*Vus)/(Sqrt[3]*fpi),
     gc97 -> (Sqrt[2/3]*GF*Vus)/fpi,
     gc98 -> -(Sqrt[2]*GF*Vud),
     gc99 -> (Sqrt[2]*GF*Vud)/fpi,
     gc100 -> (-2*GF*Vud)/(3*fpi),
     gc101 -> (-2*GF*Vus)/(3*fpi),
     gc102 -> -(Sqrt[2]*GF*Vus),
     gc103 -> (-2*GF*Vud)/(3*fpi),
     gc105 -> (4*GF*Vus)/(3*fpi),
     gc106 -> -(GF*Vus),
     gc107 -> (GF*Vus)/(3*fpi),
     gc108 -> (2*GF*Vus)/(3*fpi),
     gc109 -> 2*GF*Vud,
     gc110 -> (-4*GF*Vud)/(3*fpi),
     gc111 -> (Sqrt[2]*GF*Vus)/fpi,
     gc113 -> (4*GF*Vud)/(3*fpi),
     gc114 -> Sqrt[2]*GF*qe*Vud,
     gc115 -> 2*fpi*GF*qe*Vud,
     gc116 -> -2*GF*qe*Vud,
     gc117 -> -(Sqrt[3]*GF*qe*Vus),
     gc118 -> 2*fpi*GF*qe*Vus,
     gc119 -> -(GF*qe*Vus),
     gc120 -> Sqrt[2]*GF*qe*Vus,
     gc121 -> (Sqrt[2/3]*GF*Vud)/fpi,
     gc122 -> -(Sqrt[3]*GF*Vus),
     gc123 -> -((GF*Vus)/fpi),
     gc124 -> (GF*Vus)/(Sqrt[3]*fpi),
     gc125 -> (Sqrt[2/3]*GF*Vus)/fpi,
     gc126 -> (-2*GF*Vud)/(3*fpi),
     gc127 -> (-2*GF*Vus)/(3*fpi),
     gc128 -> Sqrt[2]*GF*Vus,
     gc129 -> Sqrt[2]*GF*Vud,
     gc130 -> (Sqrt[2]*GF*Vud)/fpi,
     gc131 -> (-2*GF*Vud)/(3*fpi),
     gc132 -> (-4*GF*Vus)/(3*fpi),
     gc134 -> GF*Vus,
     gc135 -> (GF*Vus)/(3*fpi),
     gc136 -> (-2*GF*Vus)/(3*fpi),
     gc137 -> -2*GF*Vud,
     gc138 -> (-4*GF*Vud)/(3*fpi),
     gc139 -> (Sqrt[2]*GF*Vus)/fpi,
     gc140 -> (-4*GF*Vud)/(3*fpi),
     gc142 -> (-8*fpi*GF*gsGG*qe*Vud)/(9*Lam + 4*gsGG*vs),
     gc143 -> (-8*fpi*GF*gsGG*qe*Vus)/(9*Lam + 4*gsGG*vs),
     gc144 -> (4*Sqrt[3]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs),
     gc145 -> (-4*Sqrt[2]*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs),
     gc146 -> (-4*Sqrt[2]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs),
     gc147 -> (8*fpi*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs),
     gc148 -> (-4*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs),
     gc149 -> (8*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs),
     gc150 -> (8*fpi*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs),
     gc151 -> (8*fpi*GF*gsGG*qe*Vud)/(9*Lam + 4*gsGG*vs),
     gc152 -> (8*fpi*GF*gsGG*qe*Vus)/(9*Lam + 4*gsGG*vs),
     gc153 -> (-4*Sqrt[3]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs),
     gc154 -> (4*Sqrt[2]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs),
     gc155 -> (4*Sqrt[2]*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs),
     gc156 -> (8*fpi*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs),
     gc157 -> (4*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs),
     gc158 -> (-8*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs),
     gc159 -> (8*fpi*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs)};

