(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Hazma",
  Authors -> {"Adam Coogan", "Logan Morrison"},
  Date -> "11/20/2019",
  Institutions -> {"University of Amsterdam, GRAPPA", "University of California, Santa Cruz", "Santa Cruz Institute for Particle Physics"},
  Emails -> {"a.m.coogan@uva.nl", "loanmorr@ucsc.edu"},
  URLs -> {"https://github.com/LoganAMorrison/HazmaTools", "https://github.com/LoganAMorrison/Hazma"},
  References -> {"https://arxiv.org/pdf/1907.11846.pdf"},
  Version -> 1};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["\\pi", Null, "0"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mpi0,
    Indices -> {} },

S[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["\\pi", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mpi,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> ComposedChar["K", Null, "0"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk0,
    Indices -> {} },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["K", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk,
    Indices -> {} },

S[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\eta",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> meta,
    Indices -> {} },

S[7] == {
    SelfConjugate -> True,
    PropagatorLabel -> "S",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> ms,
    Indices -> {} },

S[8] == {
    SelfConjugate -> True,
    PropagatorLabel -> "P",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mp,
    Indices -> {} },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\rho",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mrho,
    Indices -> {} },

V[3] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\omega",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> momega,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "V",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mv,
    Indices -> {} },

V[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "A",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> ma,
    Indices -> {} },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> ComposedChar["\\nu", "\\ell", Null],
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "\\ell",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> ml,
    Indices -> {} },

F[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> "\\chi",
    PropagatorArrow -> Forward,
    PropagatorType -> Straight,
    Mass -> mx,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];

mpi0[ ___ ] := mpi0;
mpi[ ___ ] := mpi;
mk0[ ___ ] := mk0;
mk[ ___ ] := mk;
meta[ ___ ] := meta;
ms[ ___ ] := ms;
mp[ ___ ] := mp;
mrho[ ___ ] := mrho;
momega[ ___ ] := momega;
mv[ ___ ] := mv;
ma[ ___ ] := ma;
ml[ ___ ] := ml;
mx[ ___ ] := mx;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[5] , S[5] , S[5] , S[5] ] == {{((I/9)*b0*(mdq + 16*msq + muq))/fpi^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[3] , -S[3] ] == {{((I/6)*b0*(mdq + 3*msq))/fpi^2, 0}, {(I/2)/fpi^2, 0}, {(-I/4)/fpi^2, 0}, {(-I/4)/fpi^2, 0}, {(-I/4)/fpi^2, 0}, {(-I/4)/fpi^2, 0}, {(I/2)/fpi^2, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(((2*I)/3)*b0*(mdq + msq))/fpi^2, 0}, {((-2*I)/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {((-2*I)/3)/fpi^2, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] ] == {{((I/6)*b0*(mdq + 2*msq + muq))/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(I/6)/fpi^2, 0}},

C[ S[5] , S[5] , S[4] , -S[4] ] == {{((I/6)*b0*(3*msq + muq))/fpi^2, 0}, {(I/2)/fpi^2, 0}, {(-I/4)/fpi^2, 0}, {(-I/4)/fpi^2, 0}, {(-I/4)/fpi^2, 0}, {(-I/4)/fpi^2, 0}, {(I/2)/fpi^2, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{(((2*I)/3)*b0*(msq + muq))/fpi^2, 0}, {((-2*I)/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {((-2*I)/3)/fpi^2, 0}},

C[ S[5] , S[5] , S[5] , S[1] ] == {{((-I/3)*b0*(mdq - muq))/(Sqrt[3]*fpi^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , S[1] ] == {{((-I/6)*b0*(mdq - msq))/(Sqrt[3]*fpi^2), 0}, {(I/4)/(Sqrt[3]*fpi^2), 0}, {(I/4)/(Sqrt[3]*fpi^2), 0}, {(-I/2)/(Sqrt[3]*fpi^2), 0}, {(-I/2)/(Sqrt[3]*fpi^2), 0}, {(I/4)/(Sqrt[3]*fpi^2), 0}, {(I/4)/(Sqrt[3]*fpi^2), 0}},

C[ S[5] , S[4] , -S[4] , S[1] ] == {{((-I/6)*b0*(msq - muq))/(Sqrt[3]*fpi^2), 0}, {(-I/4)/(Sqrt[3]*fpi^2), 0}, {(-I/4)/(Sqrt[3]*fpi^2), 0}, {(I/2)/(Sqrt[3]*fpi^2), 0}, {(I/2)/(Sqrt[3]*fpi^2), 0}, {(-I/4)/(Sqrt[3]*fpi^2), 0}, {(-I/4)/(Sqrt[3]*fpi^2), 0}},

C[ S[5] , S[5] , S[1] , S[1] ] == {{((I/3)*b0*(mdq + muq))/fpi^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{((I/6)*b0*(3*mdq + msq))/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(-I/12)/fpi^2, 0}, {(-I/12)/fpi^2, 0}, {(-I/12)/fpi^2, 0}, {(-I/12)/fpi^2, 0}, {(I/6)/fpi^2, 0}},

C[ S[4] , -S[4] , S[1] , S[1] ] == {{((I/6)*b0*(msq + 3*muq))/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(-I/12)/fpi^2, 0}, {(-I/12)/fpi^2, 0}, {(-I/12)/fpi^2, 0}, {(-I/12)/fpi^2, 0}, {(I/6)/fpi^2, 0}},

C[ S[5] , S[1] , S[1] , S[1] ] == {{((-I)*b0*(mdq - muq))/(Sqrt[3]*fpi^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(I*b0*(mdq + muq))/fpi^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] ] == {{((I/6)*b0*(mdq - 2*msq + muq))/(Sqrt[6]*fpi^2), 0}, {(-I/2)/(Sqrt[6]*fpi^2), 0}, {(-I/2)/(Sqrt[6]*fpi^2), 0}, {I/(Sqrt[6]*fpi^2), 0}, {I/(Sqrt[6]*fpi^2), 0}, {(-I/2)/(Sqrt[6]*fpi^2), 0}, {(-I/2)/(Sqrt[6]*fpi^2), 0}},

C[ -S[3] , -S[4] , S[1] , S[2] ] == {{((-I/6)*b0*(mdq - muq))/(Sqrt[2]*fpi^2), 0}, {0, 0}, {(-I/2)/(Sqrt[2]*fpi^2), 0}, {(I/2)/(Sqrt[2]*fpi^2), 0}, {(I/2)/(Sqrt[2]*fpi^2), 0}, {(-I/2)/(Sqrt[2]*fpi^2), 0}, {0, 0}},

C[ S[5] , S[3] , S[4] , -S[2] ] == {{((I/6)*b0*(mdq - 2*msq + muq))/(Sqrt[6]*fpi^2), 0}, {(-I/2)/(Sqrt[6]*fpi^2), 0}, {(-I/2)/(Sqrt[6]*fpi^2), 0}, {I/(Sqrt[6]*fpi^2), 0}, {I/(Sqrt[6]*fpi^2), 0}, {(-I/2)/(Sqrt[6]*fpi^2), 0}, {(-I/2)/(Sqrt[6]*fpi^2), 0}},

C[ S[3] , S[4] , S[1] , -S[2] ] == {{((-I/6)*b0*(mdq - muq))/(Sqrt[2]*fpi^2), 0}, {0, 0}, {(-I/2)/(Sqrt[2]*fpi^2), 0}, {(I/2)/(Sqrt[2]*fpi^2), 0}, {(I/2)/(Sqrt[2]*fpi^2), 0}, {(-I/2)/(Sqrt[2]*fpi^2), 0}, {0, 0}},

C[ S[5] , S[5] , S[2] , -S[2] ] == {{((I/3)*b0*(mdq + muq))/fpi^2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] ] == {{((I/6)*b0*(2*mdq + msq + muq))/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {(I/6)/fpi^2, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] ] == {{((I/6)*b0*(mdq + msq + 2*muq))/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(I/6)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {(I/6)/fpi^2, 0}},

C[ S[5] , S[1] , S[2] , -S[2] ] == {{((-I/3)*b0*(mdq - muq))/(Sqrt[3]*fpi^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] ] == {{((I/3)*b0*(mdq + muq))/fpi^2, 0}, {((2*I)/3)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {(-I/3)/fpi^2, 0}, {((2*I)/3)/fpi^2, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] ] == {{(((2*I)/3)*b0*(mdq + muq))/fpi^2, 0}, {((-2*I)/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {(I/3)/fpi^2, 0}, {((-2*I)/3)/fpi^2, 0}},

C[ S[5] , S[5] , S[7] ] == {{((-I/243)*b0*(mdq + 4*msq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Lam^3*vh^2), 0}, {((-4*I)*gsGG)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[5] , S[5] , S[7] ] == {{((I/729)*b0*(mdq + 16*msq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[7] ] == {{((-I/81)*b0*(mdq + msq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Lam^3*vh^2), 0}, {((-4*I)*gsGG)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[3] , -S[3] , S[7] ] == {{((I/486)*b0*(mdq + 3*msq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {((2*I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((2*I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] , S[7] ] == {{(((2*I)/243)*b0*(mdq + msq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {(((-8*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-8*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] , S[7] ] == {{((I/486)*b0*(mdq + 2*msq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[7] ] == {{((-I/81)*b0*(msq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Lam^3*vh^2), 0}, {((-4*I)*gsGG)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[4] , -S[4] , S[7] ] == {{((I/486)*b0*(3*msq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {((2*I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((2*I)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] , S[7] ] == {{(((2*I)/243)*b0*(msq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {(((-8*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-8*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[7] ] == {{((I/81)*b0*(mdq - muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[3]*Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[5] , S[1] , S[7] ] == {{((-I/243)*b0*(mdq - muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[3]*fpi^2*Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , S[1] , S[7] ] == {{((-I/486)*b0*(mdq - msq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[3]*fpi^2*Lam^3*vh^2), 0}, {(I*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(I*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-2*I)*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-2*I)*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(I*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(I*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[4] , -S[4] , S[1] , S[7] ] == {{((-I/486)*b0*(msq - muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[3]*fpi^2*Lam^3*vh^2), 0}, {((-I)*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((2*I)*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((2*I)*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*gsGG)/(Sqrt[3]*fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[7] ] == {{((-I/81)*b0*(mdq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Lam^3*vh^2), 0}, {((-4*I)*gsGG)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[1] , S[1] , S[7] ] == {{((I/243)*b0*(mdq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] , S[1] , S[7] ] == {{((I/486)*b0*(3*mdq + msq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[1] , S[1] , S[7] ] == {{((I/486)*b0*(msq + 3*muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[1] , S[1] , S[7] ] == {{((-I/81)*b0*(mdq - muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[3]*fpi^2*Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[7] ] == {{((I/81)*b0*(mdq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] , S[7] ] == {{((I/486)*b0*(mdq - 2*msq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[6]*fpi^2*Lam^3*vh^2), 0}, {((-I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((2*I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((2*I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] , S[7] ] == {{((-I/486)*b0*(mdq - muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[2]*fpi^2*Lam^3*vh^2), 0}, {0, 0}, {((-I)*Sqrt[2]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(I*Sqrt[2]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(I*Sqrt[2]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*Sqrt[2]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , S[4] , -S[2] , S[7] ] == {{((I/486)*b0*(mdq - 2*msq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[6]*fpi^2*Lam^3*vh^2), 0}, {((-I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((2*I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((2*I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*Sqrt[2/3]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , S[4] , S[1] , -S[2] , S[7] ] == {{((-I/486)*b0*(mdq - muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[2]*fpi^2*Lam^3*vh^2), 0}, {0, 0}, {((-I)*Sqrt[2]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(I*Sqrt[2]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(I*Sqrt[2]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {((-I)*Sqrt[2]*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , S[7] ] == {{((-I/81)*b0*(mdq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Lam^3*vh^2), 0}, {((-4*I)*gsGG)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[2] , -S[2] , S[7] ] == {{((I/243)*b0*(mdq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] , S[7] ] == {{((I/486)*b0*(2*mdq + msq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] , S[7] ] == {{((I/486)*b0*(mdq + msq + 2*muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((2*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[2] , -S[2] , S[7] ] == {{((-I/243)*b0*(mdq - muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(Sqrt[3]*fpi^2*Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , S[7] ] == {{((I/243)*b0*(mdq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {(((8*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((8*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , S[7] ] == {{(((2*I)/243)*b0*(mdq + muq)*(-2*gsGG*vh*vs + 3*Lam*(vh - gsff*vs))*(2*gsGG*vh*(9*Lam - 4*gsGG*vs) + 9*gsff*Lam*(3*Lam + 4*gsGG*vs)))/(fpi^2*Lam^3*vh^2), 0}, {(((-8*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((4*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {(((-8*I)/3)*gsGG)/(fpi^2*(9*Lam + 4*gsGG*vs)), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[7] , S[7] ] == {{(((-4*I)/243)*b0*gsGG*(mdq + 4*msq + muq)*(-9*gsff*Lam + 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[7] , S[7] ] == {{(((-4*I)/81)*b0*gsGG*(mdq + msq)*(-9*gsff*Lam + 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[7] , S[7] ] == {{(((-4*I)/81)*b0*gsGG*(msq + muq)*(-9*gsff*Lam + 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[1] , S[7] , S[7] ] == {{(((4*I)/81)*b0*gsGG*(mdq - muq)*(-9*gsff*Lam + 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(Sqrt[3]*Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[7] , S[7] ] == {{(((-4*I)/81)*b0*gsGG*(mdq + muq)*(-9*gsff*Lam + 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , S[7] , S[7] ] == {{(((-4*I)/81)*b0*gsGG*(mdq + muq)*(-9*gsff*Lam + 2*gsGG*vh)*(-3*Lam*vh + 3*gsff*Lam*vs + 2*gsGG*vh*vs))/(Lam^3*vh^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{(2*I)*qe^2, 0}},

C[ S[2] , -S[2] , V[1] , V[1] ] == {{(2*I)*qe^2, 0}},

C[ S[4] , -S[4] , S[7] , V[1] , V[1] ] == {{((8*I)*gsGG*qe^2)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , S[7] , V[1] , V[1] ] == {{((8*I)*gsGG*qe^2)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] , V[1] ] == {{((-I/2)*Sqrt[3/2]*qe)/fpi^2, 0}, {((I/2)*Sqrt[3/2]*qe)/fpi^2, 0}, {((I/2)*qe)/(Sqrt[6]*fpi^2), 0}, {((-I/2)*qe)/(Sqrt[6]*fpi^2), 0}},

C[ S[5] , S[3] , S[4] , -S[2] , V[1] ] == {{((I/2)*Sqrt[3/2]*qe)/fpi^2, 0}, {((-I/2)*Sqrt[3/2]*qe)/fpi^2, 0}, {((-I/2)*qe)/(Sqrt[6]*fpi^2), 0}, {((I/2)*qe)/(Sqrt[6]*fpi^2), 0}},

C[ S[3] , -S[3] , S[4] , -S[4] , V[1] ] == {{((-I/2)*qe)/fpi^2, 0}, {((I/2)*qe)/fpi^2, 0}, {((I/6)*qe)/fpi^2, 0}, {((-I/6)*qe)/fpi^2, 0}},

C[ S[3] , S[4] , S[1] , -S[2] , V[1] ] == {{((I/2)*qe)/(Sqrt[2]*fpi^2), 0}, {((-I/2)*qe)/(Sqrt[2]*fpi^2), 0}, {((-I/2)*qe)/(Sqrt[2]*fpi^2), 0}, {((I/2)*qe)/(Sqrt[2]*fpi^2), 0}},

C[ S[3] , -S[3] , S[2] , -S[2] , V[1] ] == {{((I/2)*qe)/fpi^2, 0}, {((-I/2)*qe)/fpi^2, 0}, {((I/6)*qe)/fpi^2, 0}, {((-I/6)*qe)/fpi^2, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] , V[1] ] == {{((-I/2)*qe)/(Sqrt[2]*fpi^2), 0}, {((I/2)*qe)/(Sqrt[2]*fpi^2), 0}, {((I/2)*qe)/(Sqrt[2]*fpi^2), 0}, {((-I/2)*qe)/(Sqrt[2]*fpi^2), 0}},

C[ S[4] , -S[4] , V[1] ] == {{(-I)*qe, 0}, {I*qe, 0}},

C[ S[5] , S[5] , S[4] , -S[4] , V[1] ] == {{0, 0}, {0, 0}, {((I/2)*qe)/fpi^2, 0}, {((-I/2)*qe)/fpi^2, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] , V[1] ] == {{(((4*I)/3)*qe)/fpi^2, 0}, {(((4*I)/3)*qe)/fpi^2, 0}, {(((-4*I)/3)*qe)/fpi^2, 0}, {(((-4*I)/3)*qe)/fpi^2, 0}},

C[ S[5] , S[4] , -S[4] , S[1] , V[1] ] == {{0, 0}, {((I/2)*qe)/(Sqrt[3]*fpi^2), 0}, {((-I/2)*qe)/(Sqrt[3]*fpi^2), 0}, {0, 0}},

C[ S[4] , -S[4] , S[1] , S[1] , V[1] ] == {{((I/6)*qe)/fpi^2, 0}, {((-I/6)*qe)/fpi^2, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] , V[1] ] == {{(((2*I)/3)*qe)/fpi^2, 0}, {(((-2*I)/3)*qe)/fpi^2, 0}, {(((2*I)/3)*qe)/fpi^2, 0}, {(((-2*I)/3)*qe)/fpi^2, 0}},

C[ S[4] , -S[4] , S[7] , V[1] ] == {{((-4*I)*gsGG*qe)/(9*Lam + 4*gsGG*vs), 0}, {((4*I)*gsGG*qe)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[1] ] == {{(-I)*qe, 0}, {I*qe, 0}},

C[ S[1] , S[1] , S[2] , -S[2] , V[1] ] == {{0, 0}, {0, 0}, {(((2*I)/3)*qe)/fpi^2, 0}, {(((-2*I)/3)*qe)/fpi^2, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] , V[1] ] == {{(((4*I)/3)*qe)/fpi^2, 0}, {(((4*I)/3)*qe)/fpi^2, 0}, {(((-4*I)/3)*qe)/fpi^2, 0}, {(((-4*I)/3)*qe)/fpi^2, 0}},

C[ S[2] , -S[2] , S[7] , V[1] ] == {{((-4*I)*gsGG*qe)/(9*Lam + 4*gsGG*vs), 0}, {((4*I)*gsGG*qe)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[7] , V[1] , V[1] ] == {{(I*alphaEM*gsFF)/(Lam*Pi), 0}, {((-I)*alphaEM*gsFF)/(Lam*Pi), 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , S[7] ] == {{(-I)*gsll, 0}, {(-I)*gsll, 0}, {0, 0}, {0, 0}},

C[ -F[3] , F[3] , S[7] ] == {{(-I)*gsxx, 0}, {(-I)*gsxx, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {((-I/4)*Sqrt[3]*qe)/(fpi^3*Pi^2), 0}, {0, 0}},

C[ S[5] , S[4] , -S[4] , V[1] , V[1] ] == {{0, 0}, {((-I/8)*qe^2)/(Sqrt[3]*fpi^3*Pi^2), 0}, {((I/8)*qe^2)/(Sqrt[3]*fpi^3*Pi^2), 0}, {((I/8)*qe^2)/(Sqrt[3]*fpi^3*Pi^2), 0}, {((-I/8)*qe^2)/(Sqrt[3]*fpi^3*Pi^2), 0}, {((I/8)*qe^2)/(Sqrt[3]*fpi^3*Pi^2), 0}, {((-I/8)*qe^2)/(Sqrt[3]*fpi^3*Pi^2), 0}},

C[ S[3] , S[4] , -S[2] , V[1] , V[1] ] == {{0, 0}, {((-I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((-I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((-I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}},

C[ -S[3] , -S[4] , S[2] , V[1] , V[1] ] == {{0, 0}, {((-I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((-I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((-I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}, {((I/12)*qe^2)/(Sqrt[2]*fpi^3*Pi^2), 0}},

C[ S[5] , S[4] , -S[4] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {((-I/4)*qe)/(Sqrt[3]*fpi^3*Pi^2), 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {((I/4)*qe)/(fpi^3*Pi^2), 0}, {0, 0}},

C[ S[4] , -S[4] , S[1] , V[1] , V[1] ] == {{0, 0}, {((I/24)*qe^2)/(fpi^3*Pi^2), 0}, {((-I/24)*qe^2)/(fpi^3*Pi^2), 0}, {((I/24)*qe^2)/(fpi^3*Pi^2), 0}, {((-I/24)*qe^2)/(fpi^3*Pi^2), 0}, {(((-5*I)/24)*qe^2)/(fpi^3*Pi^2), 0}, {(((5*I)/24)*qe^2)/(fpi^3*Pi^2), 0}},

C[ S[4] , -S[4] , S[1] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {((-I/4)*qe)/(fpi^3*Pi^2), 0}, {0, 0}},

C[ S[5] , S[2] , -S[2] , V[1] , V[1] ] == {{0, 0}, {((-I/4)*qe^2)/(Sqrt[3]*fpi^3*Pi^2), 0}, {((I/4)*qe^2)/(Sqrt[3]*fpi^3*Pi^2), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[2] , -S[2] , V[1] , V[1] ] == {{0, 0}, {((-I/6)*qe^2)/(fpi^3*Pi^2), 0}, {((I/6)*qe^2)/(fpi^3*Pi^2), 0}, {((I/12)*qe^2)/(fpi^3*Pi^2), 0}, {((-I/12)*qe^2)/(fpi^3*Pi^2), 0}, {((I/12)*qe^2)/(fpi^3*Pi^2), 0}, {((-I/12)*qe^2)/(fpi^3*Pi^2), 0}},

C[ S[5] , S[2] , -S[2] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {((-I/4)*qe)/(Sqrt[3]*fpi^3*Pi^2), 0}, {0, 0}},

C[ S[1] , S[2] , -S[2] , V[1] ] == {{0, 0}, {0, 0}, {0, 0}, {((-I/4)*qe)/(fpi^3*Pi^2), 0}, {0, 0}},

C[ S[5] , V[1] , V[1] ] == {{0, 0}, {0, 0}, {((I/8)*qe^2)/(Sqrt[3]*fpi*Pi^2), 0}, {((-I/8)*qe^2)/(Sqrt[3]*fpi*Pi^2), 0}},

C[ S[1] , V[1] , V[1] ] == {{0, 0}, {0, 0}, {((I/8)*qe^2)/(fpi*Pi^2), 0}, {((-I/8)*qe^2)/(fpi*Pi^2), 0}},

C[ -F[2] , F[2] , V[1] ] == {{(-I)*qe, 0}, {(-I)*qe, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , V[1] ] == {{I*Sqrt[2]*GF*qe*Vud, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , V[1] ] == {{-2*fpi*GF*qe*Vud, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] , V[1] ] == {{(-2*I)*GF*qe*Vud, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , V[1] ] == {{(-I)*Sqrt[3]*GF*qe*Vus, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , V[1] ] == {{-2*fpi*GF*qe*Vus, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , V[1] ] == {{(-I)*GF*qe*Vus, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] , V[1] ] == {{I*Sqrt[2]*GF*qe*Vus, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[3] , S[4] ] == {{(-2*Sqrt[2/3]*GF*Vud)/fpi, 0}, {(Sqrt[2/3]*GF*Vud)/fpi, 0}, {(Sqrt[2/3]*GF*Vud)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] ] == {{(-I)*Sqrt[3]*GF*Vus, 0}, {I*Sqrt[3]*GF*Vus, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[5] , S[4] ] == {{(GF*Vus)/fpi, 0}, {(GF*Vus)/fpi, 0}, {(-2*GF*Vus)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , S[1] ] == {{(GF*Vus)/(Sqrt[3]*fpi), 0}, {(-2*GF*Vus)/(Sqrt[3]*fpi), 0}, {(GF*Vus)/(Sqrt[3]*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , -S[3] , S[2] ] == {{(Sqrt[2/3]*GF*Vus)/fpi, 0}, {(-2*Sqrt[2/3]*GF*Vus)/fpi, 0}, {(Sqrt[2/3]*GF*Vus)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] ] == {{I*Sqrt[2]*GF*Vud, 0}, {(-I)*Sqrt[2]*GF*Vud, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , S[1] ] == {{-((Sqrt[2]*GF*Vud)/fpi), 0}, {(Sqrt[2]*GF*Vud)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , -S[3] , S[2] ] == {{(-2*GF*Vud)/(3*fpi), 0}, {(4*GF*Vud)/(3*fpi), 0}, {(-2*GF*Vud)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , -S[3] , S[4] ] == {{(4*GF*Vus)/(3*fpi), 0}, {(-2*GF*Vus)/(3*fpi), 0}, {(-2*GF*Vus)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] ] == {{I*Sqrt[2]*GF*Vus, 0}, {(-I)*Sqrt[2]*GF*Vus, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , -S[4] , S[2] ] == {{(-2*GF*Vud)/(3*fpi), 0}, {(4*GF*Vud)/(3*fpi), 0}, {(-2*GF*Vud)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] ] == {{0, 0}, {0, 0}, {2*fpi*GF*Vus, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[4] , -S[4] ] == {{(-4*GF*Vus)/(3*fpi), 0}, {(-4*GF*Vus)/(3*fpi), 0}, {(8*GF*Vus)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] ] == {{I*GF*Vus, 0}, {(-I)*GF*Vus, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , S[1] ] == {{(-2*GF*Vus)/(3*fpi), 0}, {(GF*Vus)/(3*fpi), 0}, {(GF*Vus)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[2] , -S[2] ] == {{(-2*GF*Vus)/(3*fpi), 0}, {(-2*GF*Vus)/(3*fpi), 0}, {(4*GF*Vus)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] ] == {{(-2*I)*GF*Vud, 0}, {(2*I)*GF*Vud, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[1] , S[2] ] == {{(4*GF*Vud)/(3*fpi), 0}, {(4*GF*Vud)/(3*fpi), 0}, {(-8*GF*Vud)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[1] , S[2] ] == {{0, 0}, {-((Sqrt[2]*GF*Vus)/fpi), 0}, {(Sqrt[2]*GF*Vus)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] ] == {{0, 0}, {0, 0}, {2*fpi*GF*Vud, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , S[2] , -S[2] ] == {{(-4*GF*Vud)/(3*fpi), 0}, {(-4*GF*Vud)/(3*fpi), 0}, {(8*GF*Vud)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , V[1] ] == {{I*Sqrt[2]*GF*qe*Vud, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , V[1] ] == {{2*fpi*GF*qe*Vud, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] , V[1] ] == {{(-2*I)*GF*qe*Vud, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , V[1] ] == {{(-I)*Sqrt[3]*GF*qe*Vus, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , V[1] ] == {{2*fpi*GF*qe*Vus, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , V[1] ] == {{(-I)*GF*qe*Vus, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] , V[1] ] == {{I*Sqrt[2]*GF*qe*Vus, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[3] , -S[4] ] == {{(-2*Sqrt[2/3]*GF*Vud)/fpi, 0}, {(Sqrt[2/3]*GF*Vud)/fpi, 0}, {(Sqrt[2/3]*GF*Vud)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] ] == {{I*Sqrt[3]*GF*Vus, 0}, {(-I)*Sqrt[3]*GF*Vus, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , S[5] , -S[4] ] == {{(GF*Vus)/fpi, 0}, {(GF*Vus)/fpi, 0}, {(-2*GF*Vus)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , S[1] ] == {{(GF*Vus)/(Sqrt[3]*fpi), 0}, {(-2*GF*Vus)/(Sqrt[3]*fpi), 0}, {(GF*Vus)/(Sqrt[3]*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , S[3] , -S[2] ] == {{(Sqrt[2/3]*GF*Vus)/fpi, 0}, {(-2*Sqrt[2/3]*GF*Vus)/fpi, 0}, {(Sqrt[2/3]*GF*Vus)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[3] , -S[2] ] == {{(4*GF*Vud)/(3*fpi), 0}, {(-2*GF*Vud)/(3*fpi), 0}, {(-2*GF*Vud)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[3] , -S[4] ] == {{(-2*GF*Vus)/(3*fpi), 0}, {(4*GF*Vus)/(3*fpi), 0}, {(-2*GF*Vus)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] ] == {{(-I)*Sqrt[2]*GF*Vus, 0}, {I*Sqrt[2]*GF*Vus, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] ] == {{(-I)*Sqrt[2]*GF*Vud, 0}, {I*Sqrt[2]*GF*Vud, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , S[1] ] == {{-((Sqrt[2]*GF*Vud)/fpi), 0}, {(Sqrt[2]*GF*Vud)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[4] , -S[4] , -S[2] ] == {{(4*GF*Vud)/(3*fpi), 0}, {(-2*GF*Vud)/(3*fpi), 0}, {(-2*GF*Vud)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[4] , -S[4] , -S[4] ] == {{(8*GF*Vus)/(3*fpi), 0}, {(-4*GF*Vus)/(3*fpi), 0}, {(-4*GF*Vus)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] ] == {{0, 0}, {0, 0}, {2*fpi*GF*Vus, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] ] == {{(-I)*GF*Vus, 0}, {I*GF*Vus, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , S[1] ] == {{(-2*GF*Vus)/(3*fpi), 0}, {(GF*Vus)/(3*fpi), 0}, {(GF*Vus)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[2] , -S[2] ] == {{(-2*GF*Vus)/(3*fpi), 0}, {(4*GF*Vus)/(3*fpi), 0}, {(-2*GF*Vus)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] ] == {{(2*I)*GF*Vud, 0}, {(-2*I)*GF*Vud, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , S[1] , -S[2] ] == {{(4*GF*Vud)/(3*fpi), 0}, {(4*GF*Vud)/(3*fpi), 0}, {(-8*GF*Vud)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , S[1] , -S[2] ] == {{0, 0}, {-((Sqrt[2]*GF*Vus)/fpi), 0}, {(Sqrt[2]*GF*Vus)/fpi, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[2] , -S[2] , -S[2] ] == {{(8*GF*Vud)/(3*fpi), 0}, {(-4*GF*Vud)/(3*fpi), 0}, {(-4*GF*Vud)/(3*fpi), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] ] == {{0, 0}, {0, 0}, {2*fpi*GF*Vud, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , S[7] , V[1] ] == {{(-8*fpi*GF*gsGG*qe*Vud)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[7] , V[1] ] == {{(-8*fpi*GF*gsGG*qe*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] , S[7] ] == {{((-4*I)*Sqrt[3]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {((4*I)*Sqrt[3]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] , S[7] ] == {{((4*I)*Sqrt[2]*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {((-4*I)*Sqrt[2]*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] , S[7] ] == {{((4*I)*Sqrt[2]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {((-4*I)*Sqrt[2]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[7] ] == {{(8*fpi*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] , S[7] ] == {{((4*I)*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {((-4*I)*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] , S[7] ] == {{((-8*I)*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {((8*I)*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , S[7] ] == {{(8*fpi*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , S[7] , V[1] ] == {{(8*fpi*GF*gsGG*qe*Vud)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[7] , V[1] ] == {{(8*fpi*GF*gsGG*qe*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] , S[7] ] == {{((4*I)*Sqrt[3]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {((-4*I)*Sqrt[3]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] , S[7] ] == {{((-4*I)*Sqrt[2]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {((4*I)*Sqrt[2]*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] , S[7] ] == {{((-4*I)*Sqrt[2]*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {((4*I)*Sqrt[2]*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[7] ] == {{(8*fpi*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] , S[7] ] == {{((-4*I)*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {((4*I)*GF*gsGG*Vus)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] , S[7] ] == {{((8*I)*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {((-8*I)*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , S[7] ] == {{(8*fpi*GF*gsGG*Vud)/(9*Lam + 4*gsGG*vs), 0}, {0, 0}, {0, 0}, {0, 0}}

}

