(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"EFT_MeV_DM_vector",
  Authors -> {"Adam Coogan", "Logan Morrison"},
  Date -> "4/27/2018",
  Institutions -> {"UC Santa Cruz"},
  Emails -> {"acoogan@ucsc.edu", "loanmorr@ucsc.edu"},
  Version -> 1};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> ComposedChar["\\pi", Null, "0"],
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mpi0,
    Indices -> {} },

S[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["\\pi", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mpi,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> ComposedChar["K", Null, "0"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk0,
    Indices -> {} },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> ComposedChar["K", Null, "-"],
    PropagatorArrow -> Forward,
    PropagatorType -> ScalarDash,
    Mass -> mk,
    Indices -> {} },

S[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\eta",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> meta,
    Indices -> {} },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\rho",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mrho,
    Indices -> {} },

V[3] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\omega",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> momega,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "V",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mv,
    Indices -> {} },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> ml,
    Indices -> {} },

F[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> "\\chi",
    PropagatorArrow -> Forward,
    PropagatorType -> Straight,
    Mass -> mx,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = 1;
GaugeXi[ S[3] ] = 1;
GaugeXi[ S[4] ] = 1;
GaugeXi[ S[5] ] = 1;
GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[rho];
GaugeXi[ V[3] ] = GaugeXi[omega];
GaugeXi[ V[4] ] = GaugeXi[Vec];

mpi0[ ___ ] := mpi0;
mpi[ ___ ] := mpi;
mk0[ ___ ] := mk0;
mk[ ___ ] := mk;
meta[ ___ ] := meta;
mrho[ ___ ] := mrho;
momega[ ___ ] := momega;
mv[ ___ ] := mv;
ml[ ___ ] := ml;
mx[ ___ ] := mx;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[5] , S[5] , S[5] , S[5] ] == {{I*gc1, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[5] , S[3] , -S[3] ] == {{(2*I)*b0*gc2*(mdq + 3*msq), 0}, {(6*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(-3*I)*gc2, 0}, {(6*I)*gc2, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-2*I)*b0*gc3*(mdq + msq), 0}, {(2*I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {(2*I)*gc3, 0}},

C[ S[3] , -S[3] , S[4] , -S[4] ] == {{I*b0*gc4*(mdq + 2*msq + muq), 0}, {I*gc4, 0}, {I*gc4, 0}, {(-2*I)*gc4, 0}, {(-2*I)*gc4, 0}, {I*gc4, 0}, {I*gc4, 0}},

C[ S[5] , S[5] , S[4] , -S[4] ] == {{(2*I)*b0*gc5*(3*msq + muq), 0}, {(6*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(-3*I)*gc5, 0}, {(6*I)*gc5, 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*b0*gc6*(msq + muq), 0}, {(2*I)*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {(2*I)*gc6, 0}},

C[ S[5] , S[5] , S[5] , S[1] ] == {{I*gc7, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , S[3] , -S[3] , S[1] ] == {{(-2*I)*b0*gc8*(mdq - msq), 0}, {(3*I)*gc8, 0}, {(3*I)*gc8, 0}, {(-6*I)*gc8, 0}, {(-6*I)*gc8, 0}, {(3*I)*gc8, 0}, {(3*I)*gc8, 0}},

C[ S[5] , S[4] , -S[4] , S[1] ] == {{(2*I)*b0*gc9*(msq - muq), 0}, {(3*I)*gc9, 0}, {(3*I)*gc9, 0}, {(-6*I)*gc9, 0}, {(-6*I)*gc9, 0}, {(3*I)*gc9, 0}, {(3*I)*gc9, 0}},

C[ S[5] , S[5] , S[1] , S[1] ] == {{I*gc10, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(2*I)*b0*gc11*(3*mdq + msq), 0}, {(2*I)*gc11, 0}, {(-I)*gc11, 0}, {(-I)*gc11, 0}, {(-I)*gc11, 0}, {(-I)*gc11, 0}, {(2*I)*gc11, 0}},

C[ S[4] , -S[4] , S[1] , S[1] ] == {{(2*I)*b0*gc12*(msq + 3*muq), 0}, {(2*I)*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {(2*I)*gc12, 0}},

C[ S[5] , S[1] , S[1] , S[1] ] == {{I*gc13, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{I*gc14, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[3] , -S[4] , S[2] ] == {{(-I)*b0*gc15*(mdq - 2*msq + muq), 0}, {(3*I)*gc15, 0}, {(3*I)*gc15, 0}, {(-6*I)*gc15, 0}, {(-6*I)*gc15, 0}, {(3*I)*gc15, 0}, {(3*I)*gc15, 0}},

C[ -S[3] , -S[4] , S[1] , S[2] ] == {{I*b0*gc16*(mdq - muq), 0}, {0, 0}, {(3*I)*gc16, 0}, {(-3*I)*gc16, 0}, {(-3*I)*gc16, 0}, {(3*I)*gc16, 0}, {0, 0}},

C[ S[5] , S[3] , S[4] , -S[2] ] == {{(-I)*b0*gc17*(mdq - 2*msq + muq), 0}, {(3*I)*gc17, 0}, {(3*I)*gc17, 0}, {(-6*I)*gc17, 0}, {(-6*I)*gc17, 0}, {(3*I)*gc17, 0}, {(3*I)*gc17, 0}},

C[ S[3] , S[4] , S[1] , -S[2] ] == {{I*b0*gc18*(mdq - muq), 0}, {0, 0}, {(3*I)*gc18, 0}, {(-3*I)*gc18, 0}, {(-3*I)*gc18, 0}, {(3*I)*gc18, 0}, {0, 0}},

C[ S[5] , S[5] , S[2] , -S[2] ] == {{I*gc19, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[2] , -S[2] ] == {{I*b0*gc20*(2*mdq + msq + muq), 0}, {I*gc20, 0}, {(-2*I)*gc20, 0}, {I*gc20, 0}, {I*gc20, 0}, {(-2*I)*gc20, 0}, {I*gc20, 0}},

C[ S[4] , -S[4] , S[2] , -S[2] ] == {{I*b0*gc21*(mdq + msq + 2*muq), 0}, {I*gc21, 0}, {(-2*I)*gc21, 0}, {I*gc21, 0}, {I*gc21, 0}, {(-2*I)*gc21, 0}, {I*gc21, 0}},

C[ S[5] , S[1] , S[2] , -S[2] ] == {{I*gc22, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[2] , -S[2] ] == {{I*b0*gc23*(mdq + muq), 0}, {(2*I)*gc23, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(2*I)*gc23, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] ] == {{(-2*I)*b0*gc24*(mdq + muq), 0}, {(2*I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {(2*I)*gc24, 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{I*gc25, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[1] , V[1] ] == {{I*gc26, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[1] ] == {{(-I)*gc27, 0}, {I*gc27, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[1] ] == {{(-I)*gc28, 0}, {I*gc28, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , V[3] ] == {{0, 0}, {0, 0}, {(-I)*gc29, 0}, {I*gc29, 0}},

C[ S[4] , -S[4] , V[1] , V[3] ] == {{0, 0}, {(-2*I)*gc30*gv, 0}, {(-2*I)*gc30*gv, 0}, {(-I)*fv*gc30, 0}, {(2*I)*gc30*gv, 0}, {(2*I)*gc30*gv, 0}, {I*fv*gc30, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[3] ] == {{0, 0}, {0, 0}, {(-I)*gc31, 0}, {I*gc31, 0}},

C[ S[3] , -S[3] , V[2] ] == {{0, 0}, {0, 0}, {(-I)*gc32, 0}, {I*gc32, 0}},

C[ S[4] , -S[4] , V[1] , V[2] ] == {{0, 0}, {(-2*I)*gc33*gv, 0}, {(-2*I)*gc33*gv, 0}, {(-I)*fv*gc33, 0}, {(2*I)*gc33*gv, 0}, {(2*I)*gc33*gv, 0}, {I*fv*gc33, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[2] ] == {{0, 0}, {0, 0}, {(-I)*gc34, 0}, {I*gc34, 0}},

C[ S[2] , -S[2] , V[1] , V[2] ] == {{0, 0}, {(-2*I)*gc35*gv, 0}, {(-2*I)*gc35*gv, 0}, {(-I)*fv*gc35, 0}, {(2*I)*gc35*gv, 0}, {(2*I)*gc35*gv, 0}, {I*fv*gc35, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[2] ] == {{0, 0}, {0, 0}, {(-I)*gc36, 0}, {I*gc36, 0}},

C[ S[3] , -S[3] , V[3] , V[4] ] == {{0, 0}, {0, 0}, {0, 0}, {(-I)*fv*gc37, 0}, {0, 0}, {0, 0}, {I*fv*gc37, 0}, {(-2*I)*gc37*gv, 0}, {(-2*I)*gc37*gv, 0}, {(2*I)*gc37*gv, 0}, {(2*I)*gc37*gv, 0}},

C[ S[4] , -S[4] , V[3] , V[4] ] == {{0, 0}, {0, 0}, {0, 0}, {(-I)*fv*gc38, 0}, {0, 0}, {0, 0}, {I*fv*gc38, 0}, {(-2*I)*gc38*gv, 0}, {(-2*I)*gc38*gv, 0}, {(2*I)*gc38*gv, 0}, {(2*I)*gc38*gv, 0}},

C[ S[3] , -S[3] , V[2] , V[4] ] == {{0, 0}, {0, 0}, {0, 0}, {(-I)*fv*gc39, 0}, {0, 0}, {0, 0}, {I*fv*gc39, 0}, {(-2*I)*gc39*gv, 0}, {(-2*I)*gc39*gv, 0}, {(2*I)*gc39*gv, 0}, {(2*I)*gc39*gv, 0}},

C[ S[4] , -S[4] , V[2] , V[4] ] == {{0, 0}, {0, 0}, {0, 0}, {(-I)*fv*gc40, 0}, {0, 0}, {0, 0}, {I*fv*gc40, 0}, {(-2*I)*gc40*gv, 0}, {(-2*I)*gc40*gv, 0}, {(2*I)*gc40*gv, 0}, {(2*I)*gc40*gv, 0}},

C[ S[2] , -S[2] , V[2] , V[4] ] == {{0, 0}, {0, 0}, {0, 0}, {(-I)*fv*gc41, 0}, {0, 0}, {0, 0}, {I*fv*gc41, 0}, {(-2*I)*gc41*gv, 0}, {(-2*I)*gc41*gv, 0}, {(2*I)*gc41*gv, 0}, {(2*I)*gc41*gv, 0}},

C[ S[5] , S[3] , -S[3] , V[1] ] == {{0, 0}, {I*gc42, 0}},

C[ S[5] , S[4] , -S[4] , V[1] ] == {{0, 0}, {I*gc43, 0}},

C[ S[3] , -S[3] , S[1] , V[1] ] == {{0, 0}, {I*gc44, 0}},

C[ S[4] , -S[4] , S[1] , V[1] ] == {{0, 0}, {I*gc45, 0}},

C[ S[5] , S[2] , -S[2] , V[1] ] == {{0, 0}, {I*gc46, 0}},

C[ S[1] , S[2] , -S[2] , V[1] ] == {{0, 0}, {I*gc47, 0}},

C[ S[5] , V[1] , V[1] ] == {{(-I)*gc48, 0}, {I*gc48, 0}},

C[ S[1] , V[1] , V[1] ] == {{(-I)*gc49, 0}, {I*gc49, 0}},

C[ S[5] , V[1] , V[4] ] == {{(-I)*gc50, 0}, {I*gc50, 0}},

C[ S[1] , V[1] , V[4] ] == {{(-I)*gc51, 0}, {I*gc51, 0}},

C[ -F[2] , F[2] , V[1] ] == {{I*gc52, 0}, {I*gc52, 0}},

C[ S[4] , -S[4] , V[1] , V[4] ] == {{I*gc53, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[1] , V[4] ] == {{I*gc54, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , V[4] ] == {{(-I)*gc55, 0}, {I*gc55, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[4] ] == {{(-I)*gc56, 0}, {I*gc56, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[4] ] == {{(-I)*gc57, 0}, {I*gc57, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , V[4] ] == {{I*gc58, 0}, {I*gc58, 0}},

C[ -F[3] , F[3] , V[4] ] == {{I*gc59, 0}, {I*gc59, 0}},

C[ S[3] , -S[3] , V[4] , V[4] ] == {{I*gc60, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , -S[4] , V[4] , V[4] ] == {{I*gc61, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , -S[2] , V[4] , V[4] ] == {{I*gc62, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[5] , V[4] , V[4] ] == {{(-I)*gc63, 0}, {I*gc63, 0}},

C[ S[1] , V[4] , V[4] ] == {{(-I)*gc64, 0}, {I*gc64, 0}},

C[ S[5] , S[3] , -S[3] , V[4] ] == {{0, 0}, {I*gc65, 0}},

C[ S[5] , S[4] , -S[4] , V[4] ] == {{0, 0}, {I*gc66, 0}},

C[ S[3] , -S[3] , S[1] , V[4] ] == {{0, 0}, {I*gc67, 0}},

C[ S[4] , -S[4] , S[1] , V[4] ] == {{0, 0}, {I*gc68, 0}},

C[ -S[3] , -S[4] , S[2] , V[4] ] == {{0, 0}, {I*gc69, 0}},

C[ S[3] , S[4] , -S[2] , V[4] ] == {{0, 0}, {I*gc70, 0}},

C[ S[5] , S[2] , -S[2] , V[4] ] == {{0, 0}, {I*gc71, 0}},

C[ S[1] , S[2] , -S[2] , V[4] ] == {{0, 0}, {I*gc72, 0}},

C[ -F[1] , F[2] , -S[4] , V[3] ] == {{-gc73, 0}, {gc73, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , V[2] ] == {{-gc74, 0}, {gc74, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , V[4] ] == {{0, 0}, {0, 0}, {gc75, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , V[4] ] == {{0, 0}, {0, 0}, {gc76, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , V[4] ] == {{0, 0}, {0, 0}, {gc77, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , V[4] ] == {{0, 0}, {0, 0}, {gc78, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , V[1] ] == {{0, 0}, {0, 0}, {gc79, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , V[1] ] == {{0, 0}, {0, 0}, {gc80, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[5] , S[4] ] == {{(-I)*gc81, 0}, {I*gc81, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[3] , S[4] ] == {{(-I)*gc82, 0}, {I*gc82, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , -S[3] , S[2] ] == {{(-I)*gc83, 0}, {I*gc83, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] ] == {{gc84, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , S[1] ] == {{(-I)*gc85, 0}, {I*gc85, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] , S[2] ] == {{(-I)*gc86, 0}, {I*gc86, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] ] == {{gc87, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , V[3] ] == {{-gc88, 0}, {gc88, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[4] , V[2] ] == {{-gc89, 0}, {gc89, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] , V[2] ] == {{-gc90, 0}, {gc90, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] , V[1] ] == {{0, 0}, {0, 0}, {gc91, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , V[1] ] == {{0, 0}, {0, 0}, {gc92, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[5] , -S[4] ] == {{(-I)*gc93, 0}, {I*gc93, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[3] , -S[2] ] == {{(-I)*gc94, 0}, {I*gc94, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[3] , -S[4] ] == {{(-I)*gc95, 0}, {I*gc95, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] ] == {{gc96, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , S[1] ] == {{(-I)*gc97, 0}, {I*gc97, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] , -S[2] ] == {{(-I)*gc98, 0}, {I*gc98, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[2] ] == {{gc99, 0}, {0, 0}},

C[ -F[1] , F[2] , -S[4] , V[2] ] == {{-gc100, 0}, {gc100, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> (b0*(mdq + 16*msq + muq))/(9*fpi^2),
     gc2 -> 1/(12*fpi^2),
     gc3 -> -1/(3*fpi^2),
     gc4 -> 1/(6*fpi^2),
     gc5 -> 1/(12*fpi^2),
     gc6 -> -1/(3*fpi^2),
     gc7 -> -(b0*(mdq - muq))/(3*Sqrt[3]*fpi^2),
     gc8 -> 1/(12*Sqrt[3]*fpi^2),
     gc9 -> -1/(12*Sqrt[3]*fpi^2),
     gc10 -> (b0*(mdq + muq))/(3*fpi^2),
     gc11 -> 1/(12*fpi^2),
     gc12 -> 1/(12*fpi^2),
     gc13 -> -((b0*(mdq - muq))/(Sqrt[3]*fpi^2)),
     gc14 -> (b0*(mdq + muq))/fpi^2,
     gc15 -> -1/(6*Sqrt[6]*fpi^2),
     gc16 -> -1/(6*Sqrt[2]*fpi^2),
     gc17 -> -1/(6*Sqrt[6]*fpi^2),
     gc18 -> -1/(6*Sqrt[2]*fpi^2),
     gc19 -> (b0*(mdq + muq))/(3*fpi^2),
     gc20 -> 1/(6*fpi^2),
     gc21 -> 1/(6*fpi^2),
     gc22 -> -(b0*(mdq - muq))/(3*Sqrt[3]*fpi^2),
     gc23 -> 1/(3*fpi^2),
     gc24 -> -1/(3*fpi^2),
     gc25 -> 2*qe^2,
     gc26 -> 2*qe^2,
     gc27 -> qe,
     gc28 -> qe,
     gc29 -> -((Sqrt[3]*gv)/(fpi^2*mVectorRes)),
     gc30 -> -(Sqrt[3]*qe)/(2*fpi^2*mVectorRes),
     gc31 -> (Sqrt[3]*gv)/(fpi^2*mVectorRes),
     gc32 -> gv/(fpi^2*mVectorRes),
     gc33 -> -qe/(2*fpi^2*mVectorRes),
     gc34 -> gv/(fpi^2*mVectorRes),
     gc35 -> -(qe/(fpi^2*mVectorRes)),
     gc36 -> (2*gv)/(fpi^2*mVectorRes),
     gc37 -> (Sqrt[3]*(-gvdd + gvss))/(2*fpi^2*mVectorRes),
     gc38 -> (Sqrt[3]*(gvss - gvuu))/(2*fpi^2*mVectorRes),
     gc39 -> (gvdd - gvss)/(2*fpi^2*mVectorRes),
     gc40 -> (gvss - gvuu)/(2*fpi^2*mVectorRes),
     gc41 -> (gvdd - gvuu)/(fpi^2*mVectorRes),
     gc42 -> qe/(4*Sqrt[3]*fpi^3*Pi^2),
     gc43 -> qe/(12*Sqrt[3]*fpi^3*Pi^2),
     gc44 -> -qe/(12*fpi^3*Pi^2),
     gc45 -> qe/(12*fpi^3*Pi^2),
     gc46 -> qe/(12*Sqrt[3]*fpi^3*Pi^2),
     gc47 -> qe/(12*fpi^3*Pi^2),
     gc48 -> qe^2/(24*Sqrt[3]*fpi*Pi^2),
     gc49 -> qe^2/(24*fpi*Pi^2),
     gc50 -> -((gvdd - 2*(gvss + gvuu))*qe)/(24*Sqrt[3]*fpi*Pi^2),
     gc51 -> ((gvdd + 2*gvuu)*qe)/(24*fpi*Pi^2),
     gc52 -> -qe,
     gc53 -> -2*(gvss - gvuu)*qe,
     gc54 -> -2*(gvdd - gvuu)*qe,
     gc55 -> -gvdd + gvss,
     gc56 -> -gvss + gvuu,
     gc57 -> -gvdd + gvuu,
     gc58 -> gvll,
     gc59 -> gvxx,
     gc60 -> 2*(gvdd - gvss)^2,
     gc61 -> 2*(gvss - gvuu)^2,
     gc62 -> 2*(gvdd - gvuu)^2,
     gc63 -> (gvdd^2 - 2*gvss^2 + gvuu^2)/(8*Sqrt[3]*fpi*Pi^2),
     gc64 -> (-gvdd^2 + gvuu^2)/(8*fpi*Pi^2),
     gc65 -> (-4*gvdd - 5*gvss)/(12*Sqrt[3]*fpi^3*Pi^2),
     gc66 -> (5*gvss + 4*gvuu)/(12*Sqrt[3]*fpi^3*Pi^2),
     gc67 -> (2*gvdd + gvss)/(12*fpi^3*Pi^2),
     gc68 -> (gvss + 2*gvuu)/(12*fpi^3*Pi^2),
     gc69 -> (gvdd + gvss + gvuu)/(6*Sqrt[2]*fpi^3*Pi^2),
     gc70 -> (-gvdd - gvss - gvuu)/(6*Sqrt[2]*fpi^3*Pi^2),
     gc71 -> (-gvdd + gvuu)/(12*Sqrt[3]*fpi^3*Pi^2),
     gc72 -> (gvdd + gvuu)/(4*fpi^3*Pi^2),
     gc73 -> (2*Sqrt[3]*GF*gv*Vus)/(fpi*mVectorRes),
     gc74 -> (4*GF*gv*Vud)/(fpi*mVectorRes),
     gc75 -> 2*fpi*GF*(gvdd - gvuu)*Vud,
     gc76 -> 2*fpi*GF*(gvss - gvuu)*Vus,
     gc77 -> 2*fpi*GF*(-gvdd + gvuu)*Vud,
     gc78 -> 2*fpi*GF*(-gvss + gvuu)*Vus,
     gc79 -> -2*fpi*GF*qe*Vud,
     gc80 -> -2*fpi*GF*qe*Vus,
     gc81 -> Sqrt[3]*GF*Vus,
     gc82 -> -(Sqrt[2]*GF*Vud),
     gc83 -> -(Sqrt[2]*GF*Vus),
     gc84 -> 2*fpi*GF*Vus,
     gc85 -> -(GF*Vus),
     gc86 -> 2*GF*Vud,
     gc87 -> 2*fpi*GF*Vud,
     gc88 -> (-2*Sqrt[3]*GF*gv*Vus)/(fpi*mVectorRes),
     gc89 -> (-2*GF*gv*Vus)/(fpi*mVectorRes),
     gc90 -> (-4*GF*gv*Vud)/(fpi*mVectorRes),
     gc91 -> 2*fpi*GF*qe*Vud,
     gc92 -> 2*fpi*GF*qe*Vus,
     gc93 -> -(Sqrt[3]*GF*Vus),
     gc94 -> Sqrt[2]*GF*Vus,
     gc95 -> Sqrt[2]*GF*Vud,
     gc96 -> 2*fpi*GF*Vus,
     gc97 -> GF*Vus,
     gc98 -> -2*GF*Vud,
     gc99 -> 2*fpi*GF*Vud,
     gc100 -> (2*GF*gv*Vus)/(fpi*mVectorRes)};

